name: proyecto_sistemas_info_grupo5
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  flutter_paypal_payment: ^1.0.8
  firebase_core: ^4.10.0
  url_launcher: ^6.3.0
  http: ^1.2.0
  image_picker: ^1.2.2
  firebase_storage: ^13.4.0
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/humbolt.png
    - assets/isla_la_tortuga.png
    - assets/logo_rutas.png
    - assets/logo_unimet.png
    - assets/los_roques.png
    - assets/merida.png
    - assets/morrocoy.png
    - assets/playas_sucre.png
    - assets/posada.png
    - assets/salto_angel.png
    - assets/ubicacion.png
    - assets/caba_merida.png